name: Flutter APK Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # You can change this to your Flutter version
          channel: 'stable'

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project for potential issues
      - name: Analyze project
        run: flutter analyze

      # Run tests (optional, you can remove this if not needed)
      - name: Run tests
        run: flutter test

      # Build release APK
      - name: Build APK
        run: flutter build apk --release

      # Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
